title: Tom Ootes
description: Tom Ootes is een geëngageerde software-developer, werkzaam voor de Nederlandse overheid.
author:
  name: Tom Ootes
  email: tom@ootes.io
lang: nl
feed:
  posts_limit: 20
baseurl: ""
url: "https://ootes.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _scss
17 | exclude:
18 |   - "/node_modules"
19 |   - Gemfile
20 |   - Gemfile.lock
21 |   - README.md
22 |   - package.json
23 |   - postcss.config.js
24 |   - tailwind.config.js
25 |   - _sass
26 |   - css
27 |   - js
28 |   - vendor

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: posts
    values:
      layout: blog
